-include $(ROOT_PROJECT_DIRECTORY)options.mk
-include $(ROOT_PROJECT_DIRECTORY)src/dependencies.mk
LIBRARIES= $(trace)
TARGET=$(LIB_DIRECTORY)libtrace.a
-include $(ROOT_PROJECT_DIRECTORY)src/library.mk
