-include $(ROOT_PROJECT_DIRECTORY)options.mk
-include $(ROOT_PROJECT_DIRECTORY)src/dependencies.mk
LIBRARIES= $(memimg)
TARGET=$(LIB_DIRECTORY)libmemimg.a
-include $(ROOT_PROJECT_DIRECTORY)src/library.mk
