-include $(ROOT_PROJECT_DIRECTORY)options.mk
-include $(ROOT_PROJECT_DIRECTORY)src/dependencies.mk
LIBRARIES= $(inst-builder)
TARGET=$(BIN_DIRECTORY)inst-builder
-include $(ROOT_PROJECT_DIRECTORY)src/executable.mk
