-include $(ROOT_PROJECT_DIRECTORY)options.mk
-include $(ROOT_PROJECT_DIRECTORY)src/dependencies.mk
LIBRARIES= $(zircon)
SYSTEM_LIBRARIES= popt
TARGET=$(BIN_DIRECTORY)zircon
-include $(ROOT_PROJECT_DIRECTORY)src/executable.mk
